services:
    catalog:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                - APP_NAME=catalog
        ports:
            - '3000:3000'
        command: npm run start:dev -- catalog
        environment:
            - NODE_ENV=development
            - MONGO_URI=mongodb://db:27017/catalog-db
        # volumes:
        #     - ./package.json:/usr/src/app/package.json
        #     - ./apps/catalog:/usr/src/app/apps/catalog
        depends_on:
            - db
    cart:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                - APP_NAME=cart
        ports:
            - '3001:3001'
        command: npm run start:dev -- cart
        environment:
            - NODE_ENV=development
            - REDIS_HOST=cartsdb
            - REDIS_PORT=6379
        # volumes:
        #     - ./package.json:/usr/src/app/package.json
        #     - ./apps/cart:/usr/src/app/apps/cart
        depends_on:
            - cartsdb
    db:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            - MONGO_DB=catalog-db

    cartsdb:
        image: redis
        restart: always
        ports:
            - 6379:6379
        # healthcheck:
        #     test: ['CMD', 'redis-cli', 'ping']
        #     interval: 30s
        #     timeout: 5s
        #     retries: 3

    # catalog_esb:
    #     image: rabbitmq:3-management-alpine
    #     ports:
    #         - 5672:5672
    #         - 15672:15672
